config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  devise_for :users
  resources :blogs
  resources :users
  root 'blogs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :users, optional: true
    
    validates :title, :body, presence: true
    validates :body, length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
    
  has_many :blogs, dependent: :destroy
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :user_signed_in?, only: [:create, :update, :destroy]
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def index
    @blogs = Blog.all  #paginate(page: params[:page], per_page: 10)
  end
  
  def new
    @blog = current_user.blogs.build
  end
  
  def create
    @blog = current_user.blogs.build(blog_params)
      if @blog.save
        flash[:success] = "Micropost created!"
        redirect_to root_url #, notice: 'Blog was successfully created.'
      else
        render :new
      end
  end

  def show
    REDIS.zincrby "blogs/pv", 1, @blog.id
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      redirect_to @blog #, notice: 'Blog was successfully updated.'
    else
      render :edit 
    end
  end

  def destroy
    REDIS.zrem("blogs/pv", @blog.id)
    @blog.destroy
    redirect_to blogs_url #, notice: 'Blog was successfully destroyed.'
  end

  private

    def set_blog
      @blog = Blog.find(params[:id])
    end
    
    def blog_params
      params.require(:blog).permit(:title, :body, :user_id)
    end
    
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def set_ranking_data
    @ids = REDIS.zrevrangebyscore "blogs/pv", "+inf", 0, limit: [0, 5], withscores: true
    # @ranking_blogs = ids.map{ |id, score| Blog.find(id) }
    # if @ranking_blogs.count < 5
    #   adding_blogs = Blog.order(published_at: :DESC, updated_at: :DESC).where.not(id: ids).limit(5 - @ranking_blogs.count)
    #   @ranking_blogs.concat(adding_blogs)
    # end
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_blog.html.erb
<div>
  <h2><%= link_to blog.title, blog %></h2>
  <p><%= blog.created_at.strftime("%Y/%m/%d") %></p>
  <p><% if !!current_user %>
    <%= link_to 'Edit', edit_blog_path(blog) %>
    <%= link_to 'Delete', blog, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %></p>
</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :blog_title %>
  </div>

  <div class="area">
    <%= form.label :body %>
    <%= form.text_area :body, id: :blog_body %>
  </div>

  <div class="actions">
    <%= form.submit "Post", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div id="article_wrap">
    <h1>Editing Blog</h1>
    <%= render 'form', blog: @blog %>
    
    <%= link_to 'Show', @blog %> |
    <%= link_to 'Back', root_path %>

    <%= render 'layouts/sidebar_ranking' %>
</div>

app/views/blogs/index.html.erb
<div id="main">
<%= image_tag "main-img.jpg", alt: "main photo" %>
</div>

<div id="article_wrap">
  <h2>Blogs</h2>
  
  
  <div id="article_list">
    <%= render @blogs %>
  </div>
  
  
  <%= render 'layouts/sidebar_ranking' %>
</div>

app/views/blogs/new.html.erb
<div id="article_wrap">
  <h1>New Blog</h1>
  
  <% if @blog.errors.any? %>
    <div>
      <ul>
        <% @blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

  <%= render 'form', blog: @blog %>

<%= link_to 'Back', root_path %>

<%= render 'layouts/sidebar_ranking' %>
</div>

app/views/blogs/show.html.erb
<div id="title">
  <div>
    <p>
      Written by_<%= User.find_by(id: @blog.user_id).email %>
    </p>
    <p>
      <%= @blog.created_at.strftime("%Y/%m/%d") %>
    </p>
    <h1><%= @blog.title %></h1>
  </div>
</div>

<div id="article_wrap">
  <div id="content">
    <p><%= @blog.body %></p>
    <p>
    <% if user_signed_in? %>
    <%= link_to 'Edit', edit_blog_path(@blog) %> |
    <% end %>
    <%= link_to 'Back', blogs_path %>
    </p>
  </div>

<%= render 'layouts/sidebar_ranking' %>

</div>

app/views/layouts/_sidebar_ranking.html.erb
<div id="sidebar">
  <h2>★PV数ランキング</h2>
  <% set_ranking_data %>
  <ul>
    <% @ids.each do |blog_id, pv| %>
      <% blog = Blog.find_by(id: blog_id) %>
      <li>
        <%= link_to blog do %>
          <%= "#{blog.title} " %><span><%= "(#{pv.to_i} PV)" %></span>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <header>
      <p id="logo">
        <%= link_to root_url do %>
          RailsCamp<span>Blog</span>
        <% end %>
      </p>
      <nav>
        <ul>
          <li><%= link_to "Home", root_url %></li>
          <% if user_signed_in? %>
            <li><%= link_to 'Post new Blog', new_blog_path %></li>
            <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            <li><div id="user_info"><%= current_user.email %></div></li>
          <% else %>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <li><%= link_to 'Log in', new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </header>
    
    <div id="text">
    
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% elsif alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    
    <%= yield %>

  </div>

  <footer>
    <div id="footer_inner">
        <p>Copyright RailsCamp 2015 All Rights Reserved</p>
    </div>
  </footer>
    
    <!--<%= debug(params) if Rails.env.development? %>-->
  </body>
</html>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>